#!/bin/bash

output=nuklei/LoggingMacros.h

echo "#ifndef NUKLEI_LOGGING_MACROS_H
#define NUKLEI_LOGGING_MACROS_H

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! //
// This file is auto-generated by logging_macros.sh //
// Do not edit. !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! //
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! //

#include <nuklei/Log.h>
#include <nuklei/Definitions.h>

" > $output

levelId=1
for level in FATAL ERROR WARN INFO LOG DEBUG ; do
    echo \
"
#define NUKLEI_$level(message) { \\
  if (::nuklei::LOG_LEVEL >= $levelId) {\\
  ::std::ostringstream nuklei_logging_local_o_string_stream; \\
  nuklei_logging_local_o_string_stream << message; \\
  ::nuklei::Log::log(__FILE__, __LINE__, $levelId, nuklei_logging_local_o_string_stream.str()); }}

" >> $output
levelId=$(( $levelId + 1 ))
done

echo "
#endif
" >> $output
